# Generated by Django 4.1.1 on 2022-09-27 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Asana Name')),
                ('no_of_postures', models.PositiveIntegerField(verbose_name='Number of Postures')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(verbose_name='Last Modified At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_asans', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='Posture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Posture Name')),
                ('dataset', models.FileField(upload_to='')),
                ('order', models.PositiveIntegerField(verbose_name='Posture Order')),
                ('asana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_postures', to='users.asana')),
            ],
        ),
    ]
