# Generated by Django 4.1.2 on 2024-07-15 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Asana Name')),
                ('no_of_postures', models.PositiveIntegerField(verbose_name='Number of Postures')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
                ('last_modified_at', models.DateTimeField(verbose_name='Last Modified At')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_asans', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('description', models.TextField(max_length=200)),
                ('trainee_status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT')], default='PENDING', max_length=10)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_added', to=settings.AUTH_USER_MODEL)),
                ('no_of_asanas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_asanas', to='users.asana')),
                ('no_of_posture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_postures', to='users.asana')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainee_name', to=settings.AUTH_USER_MODEL, verbose_name='Trainee Name')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('permitted_asanas', models.PositiveIntegerField(default=None)),
                ('no_of_persons_onboard', models.PositiveIntegerField(default=None)),
                ('price', models.FloatField(default=None)),
                ('highlight_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Posture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField(verbose_name='Step No')),
                ('name', models.CharField(max_length=100, verbose_name='Posture Name')),
                ('dataset', models.FileField(blank=True, null=True, upload_to='')),
                ('snap_shot', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Snap Shot')),
                ('last_modified_at', models.DateTimeField(null=True, verbose_name='Last Modified At')),
                ('first_trained_at', models.DateTimeField(null=True, verbose_name='First Trained At')),
                ('is_active', models.BooleanField(default=True)),
                ('asana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_postures', to='users.asana')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_enroll', models.DateTimeField(null=True, verbose_name='Date of Enrollment')),
                ('no_of_asanas', models.PositiveIntegerField(null=True, verbose_name='Number of Asanas')),
                ('course_validity', models.DateTimeField(blank=True, null=True, verbose_name='Course End date and time')),
                ('student_status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT')], default='PENDING', max_length=10)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments_added', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='users.coursedetails')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_enrollments', to='users.coursedetails', verbose_name='name')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='Student Name')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
