# Generated by Django 4.1.2 on 2024-07-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('permitted_asanas', models.PositiveIntegerField(default=None)),
                ('no_of_persons_onboard', models.PositiveIntegerField(default=None)),
                ('price', models.FloatField(default=None)),
                ('highlight_status', models.BooleanField(default=False)),
            ],
        ),
    ]
