# Generated by Django 4.1.2 on 2024-07-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_subscription_subscriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriptions',
            new_name='Subscription',
        ),
    ]
