# Generated by Django 4.1.1 on 2022-10-08 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_posture_snap_shot_alter_posture_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asana',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posture',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 13, 12, 28, 869691, tzinfo=datetime.timezone.utc), verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posture',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posture',
            name='last_modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 13, 12, 51, 285724, tzinfo=datetime.timezone.utc), verbose_name='Last Modified At'),
            preserve_default=False,
        ),
    ]
