# Generated by Django 4.1.1 on 2022-10-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_posture_created_at_posture_trained_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posture',
            name='step_no',
            field=models.PositiveIntegerField(default=1, verbose_name='Step No'),
            preserve_default=False,
        ),
    ]
