# Generated by Django 4.1.2 on 2024-07-23 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostureDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_for_posture', models.FloatField()),
                ('posture_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('posture_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.posture')),
            ],
        ),
    ]
