# Generated by Django 4.1.1 on 2022-10-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_posture_step_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posture',
            old_name='trained_at',
            new_name='first_trained_at',
        ),
    ]
