# Generated by Django 4.1.2 on 2024-07-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_posturedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='no_of_asanas',
        ),
        migrations.RemoveField(
            model_name='coursedetails',
            name='no_of_posture',
        ),
        migrations.RemoveField(
            model_name='enrollmentdetails',
            name='course_validity',
        ),
        migrations.RemoveField(
            model_name='enrollmentdetails',
            name='date_of_enroll',
        ),
        migrations.RemoveField(
            model_name='enrollmentdetails',
            name='no_of_asanas',
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='enrollmentdetails',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='enrollmentdetails',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='Last modified at'),
        ),
        migrations.DeleteModel(
            name='PostureDetails',
        ),
    ]
