# Generated by Django 4.1.2 on 2024-07-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_coursedetails_no_of_asanas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentdetails',
            name='course',
        ),
    ]
