# Generated by Django 4.2.4 on 2023-08-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_posture_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posture",
            name="first_trained_at",
            field=models.DateTimeField(null=True, verbose_name="First Trained At"),
        ),
    ]
