# Generated by Django 4.1.2 on 2024-07-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_coursedetails_asanas_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='asanas_created',
        ),
    ]
