# Generated by Django 4.1.2 on 2023-12-02 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_alter_posture_first_trained_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Id')),
                ('user_name', models.CharField(max_length=100, verbose_name='User Name')),
                ('user_type', models.CharField(max_length=100, verbose_name='user_type')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
