# Generated by Django 4.1.2 on 2023-12-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_data_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data_model',
            name='user_data',
        ),
    ]
