# Generated by Django 4.1.2 on 2024-07-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_postureaccuracy_numberofasana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postureaccuracy',
            name='posture_name',
        ),
    ]
