# Generated by Django 4.1.2 on 2024-07-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_postureaccuracy_posture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postureaccuracy',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
