# Generated by Django 4.1.2 on 2023-12-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_trainer_access_model_delete_user_data_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_access_model',
            name='trainer_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT')], default='PENDING', max_length=30, null=True),
        ),
    ]
