# Generated by Django 4.1.2 on 2024-01-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_student_data_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data_model',
            name='trainer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.trainer_access_model'),
        ),
    ]
