# Generated by Django 4.1.2 on 2024-07-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_numberofasana_no_of_asanas_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentdetails',
            name='asana_by_trainee',
            field=models.ManyToManyField(blank=True, related_name='course_asanas', to='users.asana'),
        ),
    ]
