# Generated by Django 4.1.2 on 2024-07-28 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_enrollmentdetails_asana_by_trainee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCodeForNegeotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('subscription_for_coupon_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_code_for_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
