# Generated by Django 4.1.2 on 2024-07-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_couponcodefornegeotiation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentdetails',
            name='trainer',
        ),
        migrations.AddField(
            model_name='enrollmentdetails',
            name='trainer',
            field=models.ManyToManyField(to='users.coursedetails'),
        ),
    ]
