# Generated by Django 4.1.2 on 2024-07-28 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_enrollmentdetails_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentdetails',
            name='trainer',
        ),
        migrations.AddField(
            model_name='enrollmentdetails',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_enrollments', to='users.coursedetails', verbose_name='name'),
        ),
    ]
