# Generated by Django 4.1.2 on 2024-07-29 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_enrollmentdetails_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='enrollmentdetails',
            name='asana_by_trainee',
        ),
        migrations.RemoveField(
            model_name='enrollmentdetails',
            name='trainer',
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='asanas_by_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asanas_created_by_trainee', to='users.asana'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='no_of_asanas_created',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentdetails',
            name='students_added_to_courses',
            field=models.ManyToManyField(blank=True, related_name='course_asanas', to='users.coursedetails'),
        ),
        migrations.DeleteModel(
            name='NumberOfAsana',
        ),
    ]
