# Generated by Django 4.1.2 on 2024-07-30 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_coursedetails_added_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='asanas_by_trainer',
        ),
    ]
