# Generated by Django 4.1.2 on 2024-07-31 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0021_remove_coursedetails_asanas_by_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
