# Generated by Django 4.1.2 on 2024-08-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_coursedetails_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Course Name'),
        ),
    ]
