# Generated by Django 4.1.2 on 2024-08-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_coursedetails_added_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetails',
            name='no_of_asanas_created',
        ),
        migrations.AddField(
            model_name='trainerlogdetail',
            name='no_of_asanas_created',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
