# Generated by Django 4.1.2 on 2024-08-04 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0025_remove_coursedetails_no_of_asanas_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentdetails',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='enrollmentdetails',
            name='student_status',
        ),
        migrations.CreateModel(
            name='StudentLogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='Last modified at')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments_added', to=settings.AUTH_USER_MODEL)),
                ('student_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
