# Generated by Django 4.1.2 on 2024-08-04 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0026_remove_enrollmentdetails_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentdetails',
            name='enrollment_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_created_for_student_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
