# Generated by Django 4.1.2 on 2024-08-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_enrollmentdetails_enrollment_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlogdetail',
            name='added_by',
        ),
    ]
