# Generated by Django 4.1.2 on 2024-08-04 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0028_remove_studentlogdetail_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentdetails',
            name='enrollment_created_by',
        ),
        migrations.AddField(
            model_name='studentlogdetail',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
